### PR TITLE
Google map

### PR DESCRIPTION
**Pull request by icwong**
finish just need to update the lat and lon

### CODE REVIEW

**Comment by mm90849491** [comment]
Stop wasting your time and afford on this, you are doing something fundamentally wrong.
Do not touch User class, which is essential to the project, before doing any planning.

**Comment by icwong** [comment]
Yeah even I knew something was wrong forget to post it.

**Comment by icwong** [comment]
I am positive that my user_controller was working, to satisfy the profile builder requirements

----- Original Message -----

**Comment by mm90849491** [comment]
I don't have time to teach you some basic software development strategy and
rails basic.
You can see your user_controller does nothing by removing that file. There
might be some views can retrieve the user data from profile table as I
suspect you had migrate your database from my geocoder branch which is not
fully developed and even contradictory to the healthy database. You should
clean up your working directory and database, as there are so many
un-tracked files on that machine. Git would not remove your local copy of
files, you need to do it manually.

**Pull request closed without merging**
