### PR TITLE
MergedNewUI

### PR DESCRIPTION
**Pull request by AmberQi1412**
This is the new UI, changed navbar and some layouts. Maybe merge it to master so that we can do the further work based on this version of UI.

### CODE REVIEW

**Comment by mm90849491** [comment]
Is this branch done?
I see there is a code block doing javascript, move it to home or text page, keep the index page clean and risk free.

**Comment by AmberQi1412** [comment]
Don't worry, I've already moved it. 
I'm still working on the branch, but is would be great if you can merge it to master
so that I can work on the new branch and enhance the UI to make it fit all the new features.

Of course U can give me any advice so that I can modify it asap. 

----- Original Message -----

**Comment by AmberQi1412** [comment]
Since my branch is way behind master, I'll try merge master to my branch so that 
it'll be easier for U to merge later. I'll let U know when I finish.

----- Original Message -----

**Comment by AmberQi1412** [comment]
...I accidentally push the changes to master. Well, I definitely did not touch anything important,
only changed the UI. 
Please take a look, and if anything goes wrong, just tell me what to change and
revert my merge anyways.
By the way, I'm working on the setting/display page, don't worry about it.

----- Original Message -----

**Comment by mm90849491** [comment]
don't worry I revert it

see the UI I reworked
new post
view post
edit post
pages need immediate rework

**Comment by AmberQi1412** [comment]
Did you see the version I pushed? If you are ok with the look, I'll try merge
the new master to it and work on the pages. 

By the way, Ivan did some work on resumebuilder and pages,
Shall I merge some of his work as well?

----- Original Message -----

**Comment by mm90849491** [comment]
master right now has almost all your branch things updated
if you do not see some features, you can list it to me, but some features
are removed as they are not functional necessary e.g. left-navibar

**Comment by AmberQi1412** [comment]
Ok then...I just made the sidebar to make the website better-looking.
I mean, part of the purpose of UI is to decorate the website,
and there's no harm to use sidenav instead of topnav. To be honest,
I was hoping these tricks can earn us a higher mark in UI. :)

Anyways, I'll work on the other pages first. 

----- Original Message -----

**Pull request merged**
